# Generated by Django 5.0.2 on 2024-03-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.IntegerField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('student_dept', models.CharField(max_length=100)),
                ('student_phno', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=100)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.college')),
            ],
        ),
    ]
